# Change these first
owner: I-GUIDE # Your GitHub organization or username, where this repository lives
repo: Status-Monitoring-with-Upptime # The name of this repository

sites:
  - name: I-GUIDE
    url: https://i-guide.io
  - name: I-GUIDE (Illinois Domain)
    url: https://iguide.illinois.edu
  - name: I-GUIDE JupyterHub Platform
    url: https://jupyter.i-guide.io/hub/login
  - name: I-GUIDE Platform User Environment
    url: https://platform.i-guide.io
  - name : I-GUIDE Platform Neo4J example API (connected-graph)
    url: https://backend.i-guide.io/api/connected-graph
  - name : I-GUIDE Platform Login Mini Backend
    url: https://platform.i-guide.io:8443

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  #cname: demo.upptime.js.org
  baseUrl: /Status-Monitoring-with-Upptime
  logoUrl: https://iguide.illinois.edu/wp-content/themes/iguide-v2/assets/images/logo-color.png
  name: I-GUIDE Status Monitoring
  introTitle: "**I-GUIDE** website status monitoring"
  introMessage: This is the status page for monitoring the status of the I-GUIDE website, the I-GUIDE Data Catalog, and the I-GUIDE JupyterHub platform.
  navbar:
    - title: Status
      href: /Status-Monitoring-with-Upptime
    - title: I-GUIDE
      href: https://iguide.illinois.edu/

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
